version: '3.8'

services:
    mysql_db:
        container_name: mysql_db
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
        image: mysql:${MYSQL_VERSION}
        platform: linux/x86_64 # used for M1 chip
        ports:
            - target: 3306
              published: ${MYSQL_HOST_PORT}
              protocol: tcp
              mode: host
        restart: always
        volumes:
            - type: bind
              source: ${MYSQL_DATA_HOST}
              target: /var/lib/mysql
